add builtins for environment exploration
42-Ikole-Systems/TMK-SH pull request #36
Opened 2023-10-21 13:01 UTC by Tishj

2023-10-21 16:37 UTC, K1ngmar commented
Other than a few minor thinks it LGTM!

2023-10-22 10:29 UTC, K1ngmar requested changes

2023-10-22 10:40 UTC, Tishj commented
LGTM

2023-10-22 10:40 UTC, K1ngmar commented
LGTM!

2023-10-22 10:48 UTC, K1ngmar approved these changes

2023-10-22 11:08 UTC, merged